apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "cloud-custodian-cron.fullname" . }}-{{ .Values.policyTemplate.name }}"
  labels:
   {{- include "cloud-custodian-cron.labels" . | nindent 4 }}
data:
  policies.yaml: |-
    policies:
      {{- toYaml .Values.policyTemplate.policies | nindent 4 }}
