apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "cloud-custodian-cron.fullname" . }}-{{ .Values.policyTemplate.name }}"
  labels:
    {{- include "cloud-custodian-cron.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.policyTemplate.concurrencyPolicy }}
  schedule: {{ .Values.policyTemplate.schedule | quote }}
  failedJobsHistoryLimit: {{ .Values.policyTemplate.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.policyTemplate.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "cloud-custodian-cron.selectorLabels" . | nindent 12 }}
        spec:
          volumes:
          - name: policy
            configMap:
              name: "{{ include "cloud-custodian-cron.fullname" . }}-{{ .Values.policyTemplate.name }}"
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "cloud-custodian-cron.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ["-v", "-s", "/home/custodian/policies.yml"]
              volumeMounts:
              - name: policy
                mountPath: /home/custodian
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
